### ISSUE TITLE
an unexpected problem occurred

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#107]
NodeXL
An unexpected problem occurred.  If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.codeplex.com/NodeXL/Thread/List.aspx.
 
 
 
Details:
 
 
 
[InvalidCastException]: Return argument has an invalid type.
 
 
 
   at System.Runtime.Remoting.Proxies.RealProxy.ValidateReturnArg(Object arg, Type paramType)
 
   at System.Runtime.Remoting.Proxies.RealProxy.PropagateOutParameters(IMessage msg, Object[] outArgs, Object returnValue)
 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
 
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
 
   at Microsoft.Office.Interop.Excel.ListColumn.get_Range()
 
   at Smrf.AppLib.ExcelColumnHider.ShowHiddenColumns(ListObject table)
 
   at Smrf.NodeXL.ExcelTemplate.GroupWorksheetReader.ReadWorksheet(Workbook workbook, ReadWorkbookContext readWorkbookContext, IGraph graph)
 
   at Smrf.NodeXL.ExcelTemplate.WorkbookReader.ReadWorkbookInternal(Workbook workbook, ReadWorkbookContext readWorkbookContext)
 
   at Smrf.NodeXL.ExcelTemplate.WorkbookReader.ReadWorkbook(Workbook workbook, ReadWorkbookContext readWorkbookContext)
 
   at Smrf.NodeXL.ExcelTemplate.TaskPane.ReadWorkbook(Boolean bLayOutGraph)
OK   

#### This work item was migrated from CodePlex
CodePlex work item ID: '23089'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@7/26/2012]
Can you tell me when this problem occurs?  Does it occur every time, or is it seemingly random?

Thanks,
    Tony

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]
