### ISSUE TITLE
After launching newly installed NodeXL template Excel 2010 shuts down; Windows XP running in Bootcamp on MacBook Pro

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#110]
Excel 2010 encounters problem and shuts down running NodeXL Template 1.0.1.21 newly installed on Windows XP running in Bootcamp on MacBook Pro
 
Shows error message:
************** Exception Text **************
System.Reflection.TargetInvocationException: Uncaught exception thrown by method called through Reflection. (Exception from HRESULT: 0x80131604)
   at System.AppDomain.Unload(AppDomain domain)
   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.CreateCustomizationDomainInternal(String solutionLocation, String manifestName, String documentName, Boolean showUIDuringDeployment, IntPtr hostServiceProvider, IntPtr& executor)
   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.Microsoft.VisualStudio.Tools.Office.Runtime.Interop.IDomainCreator.CreateCustomizationDomain(String solutionLocation, String manifestName, String documentName, Boolean showUIDuringDeployment, IntPtr hostServiceProvider, IntPtr& executor)

#### This work item was migrated from CodePlex
CodePlex work item ID: '23135'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[mmurrie@8/5/2012]
Never mind. Solution found at http://nodexl.codeplex.com/discussions/267366/

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]
