### ISSUE TITLE
System Policy Prevents Loading Manifests.

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#115]
Every time I try and load Nodexl I keep getting this pop-up message that reads on my home pc.

"System policy prevents loading manifests. For more information, please contact your administrator."

Along with this:

Exception from HRESULT: 0x800A03EC

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800A03EC): Exception from HRESULT: 0x800A03EC
   at Microsoft.VisualStudio.Tools.Office.Runtime.Interop.IActionsPaneSite.Clear()
   at Microsoft.VisualStudio.Tools.Office.Internal.ActionsPaneSiteContractAdapter.Clear()
   at Microsoft.VisualStudio.Tools.Office.Internal.IActionsPaneSiteProxy.Microsoft.VisualStudio.Tools.Applications.Runtime.IActionsPaneSite.Clear()
   at Microsoft.Office.Tools.ActionsPane.Clear()
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.set_GraphVisibility(Boolean value)
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.ThisWorkbook_Startup(Object sender, EventArgs e)
   at Microsoft.Office.Tools.Excel.Workbook.OnStartup()
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.FinishInitialization()
   at Microsoft.VisualStudio.Tools.Office.EntryPointComponentBase.Microsoft.VisualStudio.Tools.Applications.Runtime.IEntryPoint.FinishInitialization()
   at Microsoft.VisualStudio.Tools.Applications.AddInAdapter.ExecutePhase(ExecutionPhases executionPhases)
   at Microsoft.VisualStudio.Tools.Applications.AddInAdapter.CompleteInitialization()
   at Microsoft.VisualStudio.Tools.Office.Internal.OfficeAddInAdapter.ExecuteEntryPointsHelper()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4971 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Office.Runtime.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Runtime.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Runtime.v9.0.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4971 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.4926 built by: NetFXw7
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.AddIn
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.5005 built by: Win7RTMGDR
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.AddIn/3.5.0.0__b77a5c561934e089/System.AddIn.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.AddIn.Contract
    Assembly Version: 2.0.0.0
    Win32 Version: 3.5.30729.4926 built by: NetFXw7
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.AddIn.Contract/2.0.0.0__b03f5f7f11d50a3a/System.AddIn.Contract.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.Hosting.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Hosting.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Hosting.v9.0.dll
----------------------------------------
System.Deployment
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Deployment/2.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Security
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4951 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Security/2.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.ServerDocument.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.ServerDocument.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.ServerDocument.v9.0.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4977 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4980 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Office.Contract.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Contract.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Contract.v9.0.dll
----------------------------------------
Microsoft.Office.Tools.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Tools.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.v9.0.dll
----------------------------------------
Smrf.NodeXL.ExcelTemplate
    Assembly Version: 1.0.1.224
    Win32 Version: 1.0.1.224
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.NodeXL.ExcelTemplate.DLL
----------------------------------------
Microsoft.VisualStudio.Tools.Office.Excel.AddInAdapter.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Excel.AddInAdapter.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Excel.AddInAdapter.v9.0.dll
----------------------------------------
Microsoft.Office.Tools.Excel.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Tools.Excel.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.Excel.v9.0.dll
----------------------------------------
Microsoft.Office.Interop.Excel
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.6600.1000
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.Office.Interop.Excel/12.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Excel.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Office.AddInAdapter.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.AddInAdapter.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.AddInAdapter.v9.0.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.AddInAdapter.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.AddInAdapter.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.AddInAdapter.v9.0.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.Contract.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.21022.123
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Contract.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Contract.v9.0.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.4971 (win7RTMGDR.050727-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_32/mscorlib/2.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Applications.Adapter.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Adapter.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Adapter.v9.0.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Office.Excel.HostAdapter.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Excel.HostAdapter.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Excel.HostAdapter.v9.0.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Office.HostAdapter.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.HostAdapter.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.HostAdapter.v9.0.dll
----------------------------------------
Microsoft.Office.Tools.Common.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Tools.Common.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.Common.v9.0.dll
----------------------------------------
Microsoft.VisualStudio.Tools.Office.Excel.AddInProxy.v9.0
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.30729.1
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Excel.AddInProxy.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Excel.AddInProxy.v9.0.dll
----------------------------------------
office
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.4518.1014
    CodeBase: file:///C:/Windows/assembly/GAC/office/12.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
Smrf.NodeXL.Core
    Assembly Version: 1.0.1.224
    Win32 Version: 1.0.1.224
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.NodeXL.Core.DLL
----------------------------------------
Smrf.NodeXL.Algorithms
    Assembly Version: 1.0.1.224
    Win32 Version: 1.0.1.224
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.NodeXL.Algorithms.DLL
----------------------------------------
Smrf.NodeXL.ApplicationUtil
    Assembly Version: 1.0.1.224
    Win32 Version: 1.0.1.224
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.NodeXL.ApplicationUtil.DLL
----------------------------------------
Smrf.NodeXL.Visualization.Wpf
    Assembly Version: 1.0.1.224
    Win32 Version: 1.0.1.224
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.NodeXL.Visualization.Wpf.DLL
----------------------------------------
Smrf.NodeXL.Util
    Assembly Version: 1.0.1.224
    Win32 Version: 1.0.1.224
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.NodeXL.Util.DLL
----------------------------------------
WindowsBase
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.6920.5005 built by: Win7RTMGDR
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/WindowsBase/3.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.6920.5005 built by: Win7RTMGDR
    CodeBase: file:///C:/Windows/assembly/GAC_32/PresentationCore/3.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
Smrf.WinFormsControls
    Assembly Version: 1.0.1.7
    Win32 Version: 1.0.1.7
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.WinFormsControls.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.4506.4926 (NetFXw7.030729-4900)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.ServiceModel/3.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.6920.4902 built by: NetFXw7
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/WindowsFormsIntegration/3.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
Smrf.NodeXL.Control.Wpf
    Assembly Version: 1.0.1.224
    Win32 Version: 1.0.1.224
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.NodeXL.Control.Wpf.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.6920.5005 built by: Win7RTMGDR
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/PresentationFramework/3.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
Smrf.NodeXL.Layouts
    Assembly Version: 1.0.1.224
    Win32 Version: 1.0.1.224
    CodeBase: file:///C:/Users/Griffin/AppData/Local/Apps/2.0/PECKMCXN.PZZ/8VYG4E0V.P7X/smrf..vsto_ee5c3b578a613f22_0001.0000_7c8d3b216493985d/Smrf.NodeXL.Layouts.DLL
----------------------------------------

I don't know what any of this means and I've spent the last couple hours trying to find a solution for it but haven't been successful so I'm hoping someone here can help me.

#### This work item was migrated from CodePlex
CodePlex work item ID: '23460'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@10/4/2012]
[This is a duplicate of the discussion topic "System Policy Prevents Loading Manifests Pop up", at http://nodexl.codeplex.com/discussions/398068.]

-- Tony

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]
