### ISSUE TITLE
error keeps happening when importing networks from twitter

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#119]
NodeXL
An unexpected problem occurred.  If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.codeplex.com/NodeXL/Thread/List.aspx.

Details:

[IndexOutOfRangeException]: Index was outside the bounds of the array.

   at Smrf.NodeXL.ExcelTemplate.GraphImporter.ImportVertexAttributes(IGraph oSourceGraph, String[] asVertexAttributes, Dictionary`2 oVertexDictionary, ListObject oVertexTable)

   at Smrf.NodeXL.ExcelTemplate.GraphImporter.ImportVertices(IGraph oSourceGraph, String[] asVertexAttributes, ListObject oVertexTable, Range oVertexNameColumnData, Range oVisibilityColumnData)

   at Smrf.NodeXL.ExcelTemplate.GraphImporter.ImportGraph(IGraph sourceGraph, String[] edgeAttributes, String[] vertexAttributes, Boolean clearTablesFirst, Workbook destinationNodeXLWorkbook)
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.ImportGraph(IGraph oGraph, String[] oEdgeAttributes, String[] oVertexAttributes, String sImportDescription, String sSuggestedFileNameNoExtension)
OK   

#### This work item was migrated from CodePlex
CodePlex work item ID: '23742'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@12/27/2012]
This problem can occur when you have an Excel feature called "auto table expansion" turned off.  Please see the solution for this at the end of the discussion at http://nodexl.codeplex.com/discussions/264674.

-- Tony

**Comment by SMRFoundation** [comment]
[tcap479@12/27/2012]
I'll copy the solution here:

* Click the round Office Button (Excel 2007) or File tab (Excel 2010) at the upper-left corner of the Excel window.

* Select Excel Options, Proofing, AutoCorrect Options, AutoFormat As You Type.

* Check "Include new rows and columns in table."

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]
