### ISSUE TITLE
First time running error

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#126]
I'm attempting to run NodeXL for the first time and get the following error:
Name: Smrf.NodeXL.ExcelTemplate
From: file:///C:/Program Files (x86)/Social Media Research Foundation/NodeXL Excel Template/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Deployment.Application.DeploymentDownloadException: Downloading file:///C:/Program Files (x86)/Social Media Research Foundation/NodeXL Excel Template/Microsoft.GLEE.dll did not succeed. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\testuser\AppData\Local\Temp\4\Deployment\3A80TE5N.KVL\4D8TC2D0.4JE\Microsoft.GLEE.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

C:/Program Files (x86)/Social Media Research Foundation/NodeXL Excel Template/Microsoft.GLEE.dll  does exist, so I'm not sure what its really complaining about.

#### This work item was migrated from CodePlex
CodePlex work item ID: '23879'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@2/5/2013]
How are you starting NodeXL?  Are you going to the Windows Start menu, selecting "All Programs" (or "Programs" in Windows XP), and then selecting "NodeXL"?

-- Tony

**Comment by SMRFoundation** [comment]
[ShadRS@2/6/2013]
I go to Start->All Programs->NodeXL->NodeXL Template

The final step is a link to the NodeXL Template residing in NodeXL's install folder:
"C:\Program Files (x86)\Social Media Research Foundation\NodeXL Excel Template\NodeXLGraph.xltx"

**Comment by SMRFoundation** [comment]
[tcap479@2/6/2013]
Is your computer owned by a corporation or some other institution and managed by an IT department?  I ask because several problem reports we've had that include the text "access to the path...is denied" have involved IT departments that have "locked down" their computers in a way that makes NodeXL impossible to run.

-- Tony

**Comment by SMRFoundation** [comment]
[ShadRS@2/7/2013]
It is a corporate computer, but I have admin rights.  Do you know what particular settings cause the issue?  I.e. is it something we can fix by relaxing a few settings?
Thanks,
-Shad

**Comment by SMRFoundation** [comment]
[tcap479@2/7/2013]
I've tried to find such a setting and I've enlisted help from the relevant Microsoft forum, but I was not successful.  There does not seem to be a simple Windows group policy setting that can be toggled to make NodeXL work.  My best guess is that the problem you and several other people have run into is an unanticipated side effect of some unrelated security setting, but I have no idea which one.

I don't think I'm going to be able to fix this for you.  The best advice I can offer is to install NodeXL on another computer that is not under IT control, if that is at all possible.  I'm sorry you ran into this.

(We do plan to overhaul the NodeXL setup program in a way that we hope will eliminate some of the problems we've had, including these security issues, but we haven't gotten to that yet.)

-- Tony

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]

**Comment by SMRFoundation** [comment]
[Cafecito@2/26/2014]
NodeXL

I get a similar error on my personal computer, which is a 64 bit Windows 7 laptop:

Name: Smrf.NodeXL.ExcelTemplate
From: file:///C:/Program Files (x86)/Social Media Research Foundation/NodeXL Excel Template/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Users\Curt\AppData\Local\Temp\Deployment\A6W9LK70.Y7K' is denied.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

I have reinstalled the program three times, but to no avail.  Please advise.

Thanks.

-Curt

**Comment by SMRFoundation** [comment]
[tcap479@2/27/2014]
Curt:

Is your computer owned by a corporation or some other institution and managed by an IT department? I ask because several problem reports we've had that include the text "access to the path...is denied" have involved IT departments that have "locked down" their computers in a way that makes NodeXL impossible to run. 

-- Tony

**Comment by SMRFoundation** [comment]
[Cafecito@2/27/2014]
Tony,

No, the computer is my personal computer.  Hopefully, I am the only person with administrative rights to it.

It is a 64 bit Windows 7 laptop

Thank you for asking.

-Curt

**Comment by SMRFoundation** [comment]
[tcap479@2/28/2014]
This has occurred on several computers, but I've never been able to pinpoint the cause or come up with a fix.

The good news is that we're about to switch to a new NodeXL setup program, a simpler version that we hope will avoid some of the problems we've run into with the old one.  I can't say whether it will fix this particular problem, but it might.

We're currently beta testing the new setup program.  Would you like to try it?

-- Tony

**Comment by SMRFoundation** [comment]
[Cafecito@2/28/2014]
Tony,

Yes, I would like to try the new setup program.

How far is it on the beta testing?  If it is far enough along on the beta testing such that it will not damage my computer, then please send the download link to me.

Thank you.

-Curt

**Comment by SMRFoundation** [comment]
[tcap479@2/28/2014]
Curt:

The only problems we've had so far are a few network timeouts, where a connection was lost and the setup program had to be run twice.  But it is still in beta and I fully understand your wanting to keep your computer intact (personally, I never, _ever_ install beta software of any type on my main computer), so I recommend that you wait until the upcoming release is officially out for a week or so.  That will be a few weeks from now.  (It will be called "NodeXL Excel Template 2014.")

-- Tony

**Comment by SMRFoundation** [comment]
[Cafecito@3/5/2014]
Tony,

I will trust that the new program will solve the installation problem, set a reminder to check the download page in a few weeks, and order the Analyzing Social Media Networks with NodeXL: Insights from a Connected World book now.

Thanks again.

-Curt

**Comment by SMRFoundation** [comment]
[Cafecito@7/4/2014]
Tony,

Please tell me if the 6-25-2014 update on the NodeXL Excel Template 2014 (https://nodexl.codeplex.com/releases/view/117659) fixed the installation problem.  I have a 64 bit Windows 7 laptop and my Excel version is 2010.

When I tried to install the 1-23-2014 dated NodeXL Excel Template 2014 back in February 2014, I got the following error:

Name: Smrf.NodeXL.ExcelTemplate
From: file:///C:/Program Files (x86)/Social Media Research Foundation/NodeXL Excel Template/Smrf.NodeXL.ExcelTemplate.vsto 

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Users\Curt\AppData\Local\Temp\Deployment\A6W9LK70.Y7K' is denied.
at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn() 

If this version does fix the installation problem, please tell me when the Beta (?) status will be removed.

Thanks.  I am looking forward to using this software.

-Curt

**Comment by SMRFoundation** [comment]
[tcap479@7/8/2014]
Hello, Curt:

The version of NodeXL that uses the new setup program has been out since February and is stable.  We've had only a handful of problems with it among the many thousands of people who have downloaded and installed it.  It's still marked as "beta," but that's because NodeXL has _always_ been marked as beta, and _that's_ just to let people know that this is free software that hasn't had the benefit of full testing by a QA team.  (We have no QA team.  We have only a part-time developer.)

The error message you posted is a bit confusing because it mentions the old, pre-February version.  I'll ignore that and simply recommend that you try the new version, which can be found here:

http://nodexl.codeplex.com/releases/view/117659

Please note that you have to uninstall the old version before you install the new version.  Once you install the new version, you will never have to manually update it.  It auto-updates itself when new versions are released.

-- Tony
