### ISSUE TITLE
gexf and graphml export error

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#127]
NodeXL
An unexpected problem occurred.  If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.codeplex.com/NodeXL/Thread/List.aspx.

Details:

[ArgumentException]: Smrf.NodeXL.Core.Graph.GetRequiredValue: A value with the key "~AllVertexMetadataKeys" does not exist.

Parameter name: key

   at Smrf.AppLib.ArgumentChecker.ThrowArgumentException(String sMethodName, String sArgumentName, String sMessageDetails, Exception oInnerException)

   at Smrf.AppLib.ArgumentChecker.ThrowArgumentException(String sMethodName, String sArgumentName, String sMessageDetails)

   at Smrf.NodeXL.Core.GraphVertexEdgeBase.GetRequiredValue(String key, Type valueType)

   at Smrf.NodeXL.Adapters.GraphAdapterBase.GetAttributeNames(IGraph graph, Boolean forVertices)

   at Smrf.NodeXL.Adapters.GraphMLGraphAdapter.SaveGraphCore(IGraph graph, Stream stream)

   at Smrf.NodeXL.Adapters.GraphAdapterBase.SaveGraph(IGraph graph, Stream stream)

   at Smrf.NodeXL.Adapters.GraphAdapterBase.SaveGraph(IGraph graph, String filename)

   at Smrf.NodeXL.ExcelTemplate.SaveGraphMLFileDialog.SaveObject(Object oObject, String sFileName)

   at Smrf.AppLib.SaveFileDialog2.ShowDialogAndSaveObject(Object oObject)

   at Smrf.NodeXL.ExcelTemplate.SaveGraphFileDialog.ShowDialogAndSaveGraph(IGraph graph)
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.ExportToFile(ReadWorkbookContext oReadWorkbookContext, SaveGraphFileDialog oSaveGraphFileDialog)
OK   

#### This work item was migrated from CodePlex
CodePlex work item ID: '23971'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@2/23/2013]
What version of NodeXL are you using?  You can tell by going to NodeXL, Help, About in the Excel ribbon.

-- Tony

**Comment by SMRFoundation** [comment]
[verkostoanatomia@2/25/2013]
I'm using 1.0.1.229

Actually I found out the reason  for this error: there was some sort of a mismatch in the edges and vertices columns.
