### ISSUE TITLE
Error occurred while importing Twitter networks

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#129]
I tried restarting the computer, shutting it down and using different hashtags, but none of it worked. I run Office 2013 on a PC. 
NodeXL
An unexpected problem occurred.  If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.codeplex.com/NodeXL/Thread/List.aspx.

Details:

[COMException]: Microsoft Excel cannot access the file 'E:\NodeXL\NodeXL Data\Twitter\29146F00'. There are several possible reasons:

• The file name or path does not exist.
• The file is being used by another program.
• The workbook you are trying to save has the same name as a currently open workbook.

Server stack trace: 

Exception rethrown at [0]: 

   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)

   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)

   at Microsoft.Office.Interop.Excel._Workbook.SaveAs(Object Filename, Object FileFormat, Object Password, Object WriteResPassword, Object ReadOnlyRecommended, Object CreateBackup, XlSaveAsAccessMode AccessMode, Object ConflictResolution, Object AddToMru, Object TextCodepage, Object TextVisualLayout, Object Local)

   at Smrf.AppLib.ExcelUtil.SaveWorkbookAs(Workbook workbook, String workbookPath)

   at Smrf.NodeXL.ExcelTemplate.TaskAutomator.SaveWorkbookIfNeverSaved(Workbook oWorkbook, String sFolderToSaveWorkbookTo)

   at Smrf.NodeXL.ExcelTemplate.TaskAutomator.<>c__DisplayClass3.<RunReadWorkbookTasks>b__0(Object sender, GraphLaidOutEventArgs e)

   at System.EventHandler1.Invoke(Object sender, TEventArgs e)   at Smrf.AppLib.EventUtil.FireEvent[TEventArgs](Object sender, TEventArgs e, EventHandler1 eventHandler)
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.ForwardEvent[TEventArgs](TEventArgs e, EventHandler`1 oEventHandler)
OK   

Thanks!

#### This work item was migrated from CodePlex
CodePlex work item ID: '24055'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@3/11/2013]
You (or someone else, if the workbook came from another person) told NodeXL to automate the workbook after importing the Twitter network, and to save the workbook in the folder "E:\NodeXL\NodeXL Data\Twitter\29146F00" during automation.  That folder doesn't seem to exist on your computer.

To fix this problem, go to NodeXL, Graph, Automate in the Excel ribbon, select the "Save workbook to a new file if it has never been saved" task, and click the Options button.  In the "Browse for Folder" dialog box that appears, select a folder that does exist.

Or, if you don't want to save the workbook when it is automated, uncheck the "Save workbook to a new file if it has never been saved" option.

Or, if you don't want to automate the workbook after importing a Twitter network, go to NodeXL, Data, Import, Import Options and uncheck "Automate the graph after the data is imported."

If you want your changes to "stick" for all new NodeXL workbooks you create, click NodeXL, Options, Use Current for New after you make your changes.

The next version of NodeXL will have a much better error message than the one you saw in your version.

-- Tony
