### ISSUE TITLE
Error occurring while importing GraphML files

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#130]
NodeXL
An unexpected problem occurred.  If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.codeplex.com/NodeXL/Thread/List.aspx.

Details:

[ArgumentException]: The Excel application must be visible.

Parameter name: visibleExcelApplication

   at Smrf.AppLib.ExcelApplicationKiller..ctor(Application visibleExcelApplication)

   at Smrf.NodeXL.ExcelTemplate.GraphMLToNodeXLWorkbookConverter.SaveGraphToNodeXLWorkbook(XmlDocument graphMLDocument, String graphMLFilePath, String nodeXLWorkbookPath, String nodeXLWorkbookSettingsFilePath, Boolean setAutomateTasksOnOpen)

   at Smrf.NodeXL.ExcelTemplate.GraphMLFilesImporter.ImportGraphMLFilesInternal(ImportGraphMLFilesAsyncArgs oImportGraphMLFilesAsyncArgs, BackgroundWorker oBackgroundWorker, DoWorkEventArgs oDoWorkEventArgs)

   at Smrf.NodeXL.ExcelTemplate.GraphMLFilesImporter.BackgroundWorker_DoWork(Object sender, DoWorkEventArgs e)

   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
OK   

#### This work item was migrated from CodePlex
CodePlex work item ID: '24069'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@3/14/2013]
Did you happen to minimize one of the Excel windows that NodeXL creates while importing GraphML files?  They need to remain visible until the importing is done, even though they might get in the way of other work you might want to do.

-- Tony

**Comment by SMRFoundation** [comment]
[kevinbschae@3/15/2013]
The Excel windows were not minimized. As soon as I press "import", the error message appears. 

I have collected multiple GraphML files using SampleNetworkConfiguration.xml
What do I choose for "Into a new NodeXL workbook in this folder:"? Can I choose any folder?

Thanks for your help.

**Comment by SMRFoundation** [comment]
[tcap479@3/15/2013]
Yes, you can choose any folder.

I can't get this problem to occur on my own computers, so I'm having trouble figuring out what's wrong.  The error message is saying that an Excel window that is supposed to be visible (and that NodeXL attempts to *force* to be visible) is not actually visible.

I'm wondering if it has something to do with Excel versions.  What version of Office are you using?  And while I'm at it, what version of Windows do you have on your computer?  Is there anything unusual about your Office or Windows environments that you know of?

Thanks,
    Tony
