### ISSUE TITLE
Customization could not be loaded because the application domain could not be created.

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#159]
Hi!

I'm experiencing issues with NodeXL in a Windows Server 2012 RDS and Office 2013. We've succesfully installed and tested NodeXL however now it seems that users cannot open NodeXL without getting the following error:

************** Exception Text **************
Microsoft.VisualStudio.Tools.Applications.Runtime.CannotCreateCustomizationDomainException: Customization could not be loaded because the application domain could not be created. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
at System.Threading.WaitHandle.WaitMultiple(WaitHandle[] waitHandles, Int32 millisecondsTimeout, Boolean exitContext, Boolean WaitAll)
at System.Threading.WaitHandle.WaitAny(WaitHandle[] waitHandles, Int32 millisecondsTimeout, Boolean exitContext)
at Microsoft.VisualStudio.Tools.Office.Runtime.SolutionInstaller.Install(ClickOnceAddInDeploymentManager clickOnceAddInDeploymentManager, OfficeAddInDeploymentManager officeDeploymentManager, AddInInformation& info)
at Microsoft.VisualStudio.Tools.Office.Runtime.SolutionInstaller.ProcessInstallerOperation(ClickOnceAddInDeploymentManager clickOnceAddInDeploymentManager, OfficeAddInDeploymentManager officeAddInDeploymentManager, AddInInformation& info)
at Microsoft.VisualStudio.Tools.Office.Runtime.SolutionInstaller.ProcessInstallerOperation(ClickOnceAddInDeploymentManager clickOnceAddInDeploymentManager, OfficeAddInDeploymentManager officeAddInDeploymentManager, Boolean showUIDuringDeployment)
at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.GetAssemblyDataFromManifests(String solutionLocation, String manifestLocator, String documentName, Boolean showUIDuringDeployment, CustomizationType customizationType, OfficeVersion officeVersion, IHostServiceProvider interopServiceProvider)
at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.CreateCustomizationDomainInternal(String solutionLocation, String manifestName, String documentName, Boolean showUIDuringDeployment, IntPtr hostServiceProvider, Boolean useFastPath, IntPtr& executor)
--- End of inner exception stack trace ---

Any idea's on what could be causing this?

Thanks,

Jan

#### This work item was migrated from CodePlex
CodePlex work item ID: '24709'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@9/18/2013]
Hello, Jan:

Unfortunately, we don't support Excel 2013 yet.  By that I mean that we haven't had the time to test NodeXL in Excel 2013 and fix any problems that arise in the new environment.  Some people have tried it anyway and have been successful, while others, including you, have run into problems.  And the particular error message you're getting is one I haven't seen before (and I thought I had seen them all!), so I can't refer to previous problem reports for clues about fixing this one.

But that doesn't mean we can't do a bit of amateur detective work here.  You said that you "successfully installed and tested NodeXL," but that now it's failing.  What changed there?  Did you do your successful testing on a different version of Windows, or a different version of Excel, or something else?

-- Tony
