### ISSUE TITLE
Unexpected problem to import DL or Pajek file

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#173]
NodeXL

An unexpected problem occurred. If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.codeplex.com/NodeXL/Thread/List.aspx. 

Details: 

[COMException]: Eccezione da HRESULT: 0x800A03EC 

Server stack trace: 

Exception rethrown at [0]: 

in System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) 

in System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) 

in Microsoft.Office.Interop.Excel.Range.get__Default(Object RowIndex, Object ColumnIndex) 

in Smrf.AppLib.ExcelUtil.SetRangeValues(Range upperLeftCornerMarker, Object[,] values, Boolean removeFormulasFromValues) 

in Smrf.NodeXL.ExcelTemplate.GraphImporter.SetRangeValues(Range oUpperLeftCornerMarker, Object[,] aoValues, Boolean bConvertUrlsToHyperlinks) 

in Smrf.NodeXL.ExcelTemplate.GraphImporter.ImportEdges(IGraph oSourceGraph, String[] asEdgeAttributes, ListObject oEdgeTable, Range oVertex1NameColumnData, Range oVertex2NameColumnData, Boolean bAppendToTable) 

in Smrf.NodeXL.ExcelTemplate.GraphImporter.ImportGraph(IGraph sourceGraph, String[] edgeAttributes, String[] vertexAttributes, Boolean clearTablesFirst, Workbook destinationNodeXLWorkbook)
in Smrf.NodeXL.ExcelTemplate.ThisWorkbook.ImportGraph(IGraph oGraph, String[] oEdgeAttributes, String[] oVertexAttributes, String sImportDescription, String sSuggestedFileNameNoExtension)

OK

#### This work item was migrated from CodePlex
CodePlex work item ID: '24921'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[rezaei_asieh64@11/29/2013]
Hello
I want to import data from Facebook and knowing about locale and hometown of users is so important for me.
I chose locale and hometown in attribute window but I did not achieve any data about it.

**Comment by SMRFoundation** [comment]
[tcap479@11/29/2013]
Alice:

Does this happen repeatedly, or was it a seemingly random, one-time thing?

-- Tony

**Comment by SMRFoundation** [comment]
[tcap479@11/29/2013]
rezaei:

I replied to your post in Discussions at http://nodexl.codeplex.com/discussions/471526 .

-- Tony

**Comment by SMRFoundation** [comment]
[AliceCasari@11/30/2013]
Hello,

yes this happen all time!
The matrix i want to import is very big, 30000x30000. Is that the problem?
DL file with matrix small were import without problem.
how can I?
Thank you

**Comment by SMRFoundation** [comment]
[tcap479@12/3/2013]
Alice:

Yes, the problem is likely caused by the size of the matrix.

NodeXL is optimized for graphs with a few thousand edges and vertices.  Some of its features work with tens of thousands of edges and vertices if you are patient, but many things (like importing a matrix) have never been tested under those conditions.  Apparently, a 30,000 x 30,000 is exceeding some limit and causing the bug you are seeing.  I don't know when this will be fixed.

The only thing I can suggest is to use some other tool to convert the matrix to an edge list, and then import the edge list into NodeXL.  If your matrix is sparse, the edge list is likely to be much smaller than the matrix.

-- Tony

**Comment by JunhaoWang** [comment]
My edge list has 133,676,569 entries. Is it too big? Because I have the same problem but importing using .graphml format.

**Comment by JunhaoWang** [comment]
@SMRFoundation question above. My error is 
---------------------------
NodeXL
---------------------------
An unexpected problem occurred.  If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.smrfoundation.org/forums/.

Details:

[COMException]: Exception from HRESULT: 0x800A03EC

   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Microsoft.Office.Interop.Excel.Range.get__Default(Object RowIndex, Object ColumnIndex)
   at Smrf.AppLib.ExcelUtil.SetRangeValues(Range upperLeftCornerMarker, Object[,] values, Boolean removeFormulasFromValues)
   at Smrf.NodeXL.ExcelTemplate.GraphImporter.SetRangeValues(Range oUpperLeftCornerMarker, Object[,] aoValues, Boolean bConvertUrlsToHyperlinks)
   at Smrf.NodeXL.ExcelTemplate.GraphImporter.ImportEdges(IGraph oSourceGraph, String[] asEdgeAttributes, ListObject oEdgeTable, Range oVertex1NameColumnData, Range oVertex2NameColumnData, Boolean bAppendToTable)
   at Smrf.NodeXL.ExcelTemplate.GraphImporter.ImportGraph(IGraph sourceGraph, String[] edgeAttributes, String[] vertexAttributes, Boolean clearTablesFirst, Workbook destinationNodeXLWorkbook)
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.ImportGraph(IGraph oGraph, String[] oEdgeAttributes, String[] oVertexAttributes, String sGraphSource, String sGraphTerm, String sImportDescription, String sSuggestedTitle, String sSuggestedFileNameNoExtension)
---------------------------
OK   
---------------------------

**Comment by SMRFoundation** [comment]
Hello!

Yes, that is a large network!

NodeXL can manage different numbers of edges based on the available computer system resources.  The following are rough estimates:

4 GB of RAM: SMALL networks only less than a few thousand edges
8 GB of RAM: MEDIUM networks of less than 10-15 thousand edges
16GB of RAM: LARGE networks of less than 15-50 thousand edges
32 GB of RAM: VERY LARGE networks of less than 50 thousand+ edges
