### ISSUE TITLE
Windows 8.1 and Office 365

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#196]
Hi,
I've installed Nodexl on a windows 8.1 box with Excel 2013 from Office 365.
The installation works OK. When starting nodexlgraph.xltx file I get the following error: Any ideas?

I have attached the full error text. Nodexl can import from twitter and Facebook and create the data but it doesn't show a thing on the graph, just a black box.

//Jorgen
HNO3 BI AB , Sweden

************** Exception Text **************
System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at System.Threading.WaitHandle.WaitOneNative(SafeWaitHandle waitHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int64 timeout, Boolean exitContext)
   at System.Windows.Input.PenThreadWorker.WorkerAddPenContext(PenContext penContext)
   at System.Windows.Input.PenThreadPool.GetPenThreadForPenContextHelper(PenContext penContext)
   at System.Windows.Input.PenContext.Enable()
   at System.Windows.Input.PenContexts.Enable()
   at System.Windows.Input.StylusLogic.RegisterHwndForInput(InputManager inputManager, PresentationSource inputSource)
   at System.Windows.Interop.HwndStylusInputProvider..ctor(HwndSource source)
   at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   at System.Windows.Interop.HwndSource..ctor(HwndSourceParameters parameters)
   at System.Windows.Forms.Integration.ElementHost.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Integration.ElementHost.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.8000 (FX35W81RTMGDR.050727-8000)

    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
Microsoft.VisualStudio.Tools.Office.Runtime.v10.0
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Runtime.v10.0/10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Runtime.v10.0.dll
System
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.7905 (win9rel.050727-7900)

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
System.Core
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.7903 built by: Win9Rel

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
System.Configuration
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.7905 (win9rel.050727-7900)

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
System.Xml
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.7905 (win9rel.050727-7900)

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
Microsoft.VisualStudio.Tools.Applications.Hosting.v10.0
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Hosting.v10.0/10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Hosting.v10.0.dll
System.AddIn
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.7903 built by: Win9Rel

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.AddIn/3.5.0.0__b77a5c561934e089/System.AddIn.dll
Microsoft.VisualStudio.Tools.Applications.Runtime.v10.0
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Runtime.v10.0/10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Runtime.v10.0.dll
System.Deployment
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.7905 (win9rel.050727-7900)

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Deployment/2.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
System.Security
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.7905 (win9rel.050727-7900)

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Security/2.0.0.0__b03f5f7f11d50a3a/System.Security.dll
Microsoft.VisualStudio.Tools.Applications.ServerDocument.v10.0
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.ServerDocument.v10.0/10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.ServerDocument.v10.0.dll
Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.5806

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0.dll
System.Windows.Forms
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.7905 (win9rel.050727-7900)

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
System.Drawing
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.7905 (win9rel.050727-7900)

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
System.Xml.Linq
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.7903 built by: Win9Rel

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml.Linq/3.5.0.0__b77a5c561934e089/System.Xml.Linq.dll
Smrf.NodeXL.ExcelTemplate
Assembly Version: 1.0.1.251
Win32 Version: 1.0.1.251

    CodeBase: file:///C:/Users/J%F6rgen/AppData/Local/Apps/2.0/667ZW04R.633/ECQ43OBW.HN7/smrf..vsto_ee5c3b578a613f22_0001.0000_a8e59033a38c54dd/Smrf.NodeXL.ExcelTemplate.DLL
Microsoft.Office.Tools.Excel.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.5806

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Tools.Excel.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.Excel.v9.0.dll
Microsoft.Office.Tools.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.5806

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Tools.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.v9.0.dll
Microsoft.Office.Interop.Excel
Assembly Version: 15.0.0.0
Win32 Version: 15.0.4569.1507

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Interop.Excel/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Excel.dll
Microsoft.VisualStudio.Tools.Office.Excel.AddInAdapter.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.5806

    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Excel.AddInAdapter.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Excel.AddInAdapter.v9.0.dll
Microsoft.VisualStudio.Tools.Office.AddInAdapter.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.5806
CodeBase:  

... for rest of the messages pls see attached file

//Jorgen

#### Attachments
[Error Message.txt](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=NodeXL&WorkItemId=25318&FileAttachmentId=6783)

#### This work item was migrated from CodePlex
CodePlex work item ID: '25318'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@3/24/2014]
Do you have a Wacom drawing tablet connected to this computer?

-- Tony

**Comment by SMRFoundation** [comment]
[JorgenHNO3@3/24/2014]
No, I don't think so. I'm running a Sony Vaio Duo that has a penenabled screen but I think it's another solution than Wacom.
Do you think the drawing tablet software can effect the graph-software?

/Jorgen

**Comment by SMRFoundation** [comment]
[tcap479@3/24/2014]
The Wacom tablet driver has caused problems with NodeXL, and when I saw that your error message mentions drawing pens, that was the first thing I thought of.  The Wacom symptoms were different from what you're describing and you don't have a Wacom tablet, but I do think this has something to do with the touchscreen on your Sony.

Unfortunately, I think this is a bug in either the Sony drivers or the .NET Framework, which is Microsoft software that NodeXL uses.  In either case, I don't know if I'm going to be able to provide a fix for it.

However, there is one thing we can try.  Did you download and install NodeXL version 1.0.1.251, which is what you get automatically when you go to the NodeXL Downloads tab?  There is a newer version of NodeXL that happens to use a newer version of the .NET Framework.  There is a chance that this bug was fixed in the newer .NET Framework, so trying the newer version of NodeXL might be worthwhile.

Please download and install "NodeXL Excel Template 2014," which you can find here:

http://nodexl.codeplex.com/releases/view/117659

Note that you have to uninstall your older version of NodeXL before you install this one.  Complete instructions are on the page above.

Let me know what happens.

-- Tony

**Comment by SMRFoundation** [comment]
[JorgenHNO3@3/26/2014]
Thank you very much Tony!
It worked. I just uninstalled the current version and installed the 2014 template. Works like a Dream. No problem at all with the penenabled things on my Vaio.
Thanks a lot.

/Jörgen HNO3 Business Intelligence Sweden

**Comment by SMRFoundation** [comment]
[tcap479@3/26/2014]
I'm glad to hear it, Jörgen.  Thank you for letting me know.

-- Tony
