### ISSUE TITLE
HTTP redirect is not allowed for application files and assemblies

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#220]
[Copied from Brian's post at http://nodexl.codeplex.com/workitem/25547 .  -- Tony]

I am having the exact sample problem. Here is the error I am getting. I only have Excel 2007 on this machine. Is Excel 2010 required for NodeXL to install?

Thank you, Brian

Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: HTTP redirect is not allowed for application files and assemblies. Cannot download SnapGraphMetricCalculatorForCliquesOnly.exe.
at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

#### This work item was migrated from CodePlex
CodePlex work item ID: '25598'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@7/9/2014]
Hello, Brian:

This is due to an Internet Explorer security setting on your computer.  You can read about it here:

http://social.msdn.microsoft.com/Forums/windows/en-US/6e8924a0-df09-4087-aed9-b5fabf6e5840/clickonce-http-redirect-is-not-allowed-for-application-files-and-assemblies?forum=winformssetup

If this is your own personal computer, you should be able to fix it like so:

1) Open Internet Explorer.

2) Go to Tools, Internet Options.

3) In the Internet Options dialog box, select the Advanced tab.

4) On the Advanced tab, scroll down to the Security section.

5) Within the Security section, uncheck "Warn if changing between secure and not secure mode".

If this is a corporate computer maintained by an IT department, they may have checked that option for you and prevented you from changing it, in which case I do not have a solution for you.  (I hadn't even been aware of this option until I researched your question.)

-- Tony
