### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#244]
have been unable to use NodeXL as the ribbon is missing. 

IT dept decided to re-install NodeXL (after deleting NodeXL via 'Add/Remove program' and deleted App 2.0 folder). 

However error message came up with "File, NodeXLExcelTemplate.chm, has a different computed hash than specified in manifest." and details:

Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: File, NodeXLExcelTemplate.chm, has a different computed hash than specified in manifest.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

Any advice?

#### This work item was migrated from CodePlex
CodePlex work item ID: '25780'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[mcoppedg@11/5/2014]
I encountered a similar problem. Right-clicking on the setup file and choosing "Run as administrator" enabled me to install successfully.
