### ISSUE TITLE
Error during installation - Exception reading manifest

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#250]
Won't install
System Info:  Windows 8.1, 64 bit, 8GB, i7-4600U, Office 2013 (click-to-run), O365

Error is as follows:  There was an error during installation
Name:  NodeXL Excel Template
From:  http://www.nodexlgraphgallery.org/NodeXLSetup.ExcelTemplate.vsto
Error Details:
Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
Microsoft.VisualStudio.Tools.Applications.Runtime.InvalidManifestException: Exception reading manifest from http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto: the manifest may not be valid or the file could not be opened. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Xml.XmlDownloadManager.GetNonFileStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri)
   at Microsoft.VisualStudio.Tools.Applications.ServerDocument.AddCustomization(String documentPath, Uri deploymentManifestUrl)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Tools.Applications.ServerDocument.ThrowManifestException(String url, Exception inner)
   at Microsoft.VisualStudio.Tools.Applications.ServerDocument.AddCustomization(String documentPath, Uri deploymentManifestUrl)
   at Smrf.NodeXL.ExcelTemplatePostDeploymentAction.PostDeploymentAction.SetAssemblyLocationInTemplateFile(AddInPostDeploymentActionArgs args)
   at Smrf.NodeXL.ExcelTemplatePostDeploymentAction.PostDeploymentAction.Execute(AddInPostDeploymentActionArgs args)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.PostDeploymentActionsHost.Execute(Int32& lastExecutedPostAction, Uri deployManifestUri, AddInInstallationStatus installStatus, String deployManifestXml, String appManifestXml, String hostManifestXml, String[] postActionDataXmls, String productName, String version, String applicationBase, String[] assemblyClassNames, String[] assemblyNames, String[] assemblyFullNames)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.PostDeploymentActionsHost.Execute(Int32& lastExecutedPostAction, Uri deployManifestUri, AddInInstallationStatus installStatus, String deployManifestXml, String appManifestXml, String hostManifestXml, String[] postActionDataXmls, String productName, String version, String applicationBase, String[] assemblyClassNames, String[] assemblyNames, String[] assemblyFullNames)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InvokePostActions(Uri deploymentUri, AddInInstallationStatus installStatus, String deployManifestXml, String appManifestXml, ApplicationManifest manifest, String productName, String version, AppDomainSetup appDomainSetup)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

#### This work item was migrated from CodePlex
CodePlex work item ID: '25899'
Vote count: '2'

**Comment by SMRFoundation** [comment]
[kimmeyh@1/2/2015]
Found the install log file, so here are the contents of:  
C:\Users\...\AppData\Local\Temp\VSDAF9D.tmp\install.log

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 6.3.0 {version}
Running checks for package 'Windows Installer 4.5', phase BuildList
Looking up path for special folder 'WindowsFolder'
Running check with folder 'C:\Windows\System32' and file 'msi.dll'
Attempting to find file 'C:\Windows\System32\msi.dll'
File version is '5.0.9600.17399'
Setting value '5.0.9600.17399 {version}' for property 'VersionMsiDll'
The following properties have been set for package 'Windows Installer 4.5':
Property: [VersionMsiDll] = 5.0.9600.17399 {version}
Running checks for command 'WindowsInstaller4_5\WindowsXP-KB942288-v3-x86.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsi' and value '4.5': true
Result of checks for command 'WindowsInstaller4_5\WindowsXP-KB942288-v3-x86.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsXP-KB958655-v2-x86-ENU.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22299': true
Result of checks for command 'WindowsInstaller4_5\WindowsXP-KB958655-v2-x86-ENU.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsServer2003-KB942288-v4-x86.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsi' and value '4.5': true
Result of checks for command 'WindowsInstaller4_5\WindowsServer2003-KB942288-v4-x86.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsServer2003-KB958655-v2-x86-ENU.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22299': true
Result of checks for command 'WindowsInstaller4_5\WindowsServer2003-KB958655-v2-x86-ENU.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsServer2003-KB942288-v4-x64.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsi' and value '4.5': true
Result of checks for command 'WindowsInstaller4_5\WindowsServer2003-KB942288-v4-x64.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\WindowsServer2003.WindowsXP-KB958655-v2-x64-ENU.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22299': true
Result of checks for command 'WindowsInstaller4_5\WindowsServer2003.WindowsXP-KB958655-v2-x64-ENU.exe' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\Windows6.0-KB958655-v2-x86.MSU'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22308': true
Result of checks for command 'WindowsInstaller4_5\Windows6.0-KB958655-v2-x86.MSU' is 'Bypass'
Running checks for command 'WindowsInstaller4_5\Windows6.0-KB958655-v2-x64.MSU'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VersionMsiDll' and value '4.5.6001.22308': true
Result of checks for command 'WindowsInstaller4_5\Windows6.0-KB958655-v2-x64.MSU' is 'Bypass'
'Windows Installer 4.5' RunCheck result: No Install Needed
Running checks for package 'Microsoft .NET Framework 4 (x86 and x64)', phase BuildList
Reading value 'Version' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read string value '4.5.51641'
Setting value '4.5.51641 {string}' for property 'DotNet40Full_TargetVersion'
The following properties have been set for package 'Microsoft .NET Framework 4 (x86 and x64)':
Property: [DotNet40Full_TargetVersion] = 4.5.51641 {string}
Running checks for command 'DotNetFX40\dotNetFx40_Full_x86_x64.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX40\dotNetFx40_Full_x86_x64.exe' is 'Bypass'
Running checks for command 'DotNetFX40\dotNetFx40_Full_setup.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'DotNet40Full_TargetVersion' and value '4.0.30129': true
Result of checks for command 'DotNetFX40\dotNetFx40_Full_setup.exe' is 'Bypass'
'Microsoft .NET Framework 4 (x86 and x64)' RunCheck result: No Install Needed
Running checks for package 'Microsoft Visual Studio 2010 Tools for Office Runtime (x86 and x64)', phase BuildList
Reading value 'Version' of registry key 'HKLM\SOFTWARE\Microsoft\VSTO Runtime Setup\v4'
Read string value '10.0.40820'
Setting value '10.0.40820 {string}' for property 'VSTORuntimeVersionOfficeInstalled'
Reading value 'Version' of registry key 'HKLM\SOFTWARE\Microsoft\VSTO Runtime Setup\v4R'
Read string value '10.0.50903'
Setting value '10.0.50903 {string}' for property 'VSTORuntimeVersionInstalled'
The following properties have been set for package 'Microsoft Visual Studio 2010 Tools for Office Runtime (x86 and x64)':
Property: [VSTORuntimeVersionInstalled] = 10.0.50903 {string}
Property: [VSTORuntimeVersionOfficeInstalled] = 10.0.40820 {string}
Running checks for command 'VSTOR40\vstor_redist.exe'
Result of running operator 'VersionGreaterThanOrEqualTo' on property 'VSTORuntimeVersionInstalled' and value '10.0.40820': true
Result of checks for command 'VSTOR40\vstor_redist.exe' is 'Bypass'
'Microsoft Visual Studio 2010 Tools for Office Runtime (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
Application appears to be a VSTO manifest
Installing VSTO solution via vstoee

**Comment by SMRFoundation** [comment]
[kimmeyh@1/2/2015]
Have the latest version of "Microsoft Visual Studio 2010 Tools for Office Runtime" installed (10.0.50903)

Tried with non-Admin and local Admin (same error)

**Comment by SMRFoundation** [comment]
[antanse@1/6/2015]
also encouter with same error

**Comment by SMRFoundation** [comment]
[UnknownUser@1/22/2015]

**Comment by SMRFoundation** [comment]
[dianrips88@1/22/2015]
i also have same error,

**Comment by SMRFoundation** [comment]
[Franksked@1/31/2015]
The issue here is that the installation tries to retrieve the vsto-file from a URL that does not seem to available at all times:

http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto

About an hour ago the install would consistently fail due to unavailability of the website. I just retried and the install continues as it should.

**Comment by SMRFoundation** [comment]
[bdeem@12/8/2015]
__Work Around / Fix__

Change your defaultProxy to use the default credentials (your NTLM login).

Edit %windir%\Microsoft.NET\Framework\v4.0.30319\config\machine.config

Add the defaultProxy element shown below, ie

```
<configuration>
...

  <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true"/>
  </system.net>

...
</configuration>
```

[<defaultProxy> Element (Network Settings)](https://msdn.microsoft.com/en-us/library/kd3cf2ex.aspx)

> __useDefaultCredentials__
Specifies whether the default credentials for this host are used to access the web proxy. The default value is false.
