### ISSUE TITLE
Import from Email Network

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#259]
I have used NodeXL to analyse email previously and recently installed on Win8, Office 2013 accessing Exchange mailbox. When choosing the import from Email Network, and hitting OK to import email an Assertion Failed error screen appears. See attachment.

If anyone can provide advice on how to fix/workaround this it would be greatly appreciated.

Thank you.

Hunter TAFE

#### Attachments
[NodeXL error.PNG](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=NodeXL&WorkItemId=26008&FileAttachmentId=7050)

#### This work item was migrated from CodePlex
CodePlex work item ID: '26008'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[HunterTAFE@2/26/2015]
Additional Error information
---------------------------
NodeXL
---------------------------
An unexpected problem occurred.  If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.codeplex.com/NodeXL/Thread/List.aspx.



Details:



[FormatException]: An aggregated dictionary key is in the wrong format.



   at Smrf.NodeXL.ExcelTemplate.AnalyzeEmailNetworkDialog.OnAnalysisCompleted(RunWorkerCompletedEventArgs e)

   at Smrf.NodeXL.ExcelTemplate.AnalyzeEmailNetworkDialog.EmailNetworkAnalyzer_AnalysisCompleted(Object sender, RunWorkerCompletedEventArgs e)
---------------------------
OK   
---------------------------
