### ISSUE TITLE
Error with Customization Installation

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#29]
I am new to NodeXL and just installed it.  When I attempt to start up the template I receive the following error:
 
An error occured during customization install.
 
Invalid URI: The hostname could not be parsed.
 
************** Exception Text **************
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.VisualStudio.Tools.Office.Runtime.OfficeAddInDeploymentManager.OnAddInInstalling(AddInInstallingArgs args, Boolean& cancel)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.RaiseOnAddInInstallingEvent(IClickOnceAddInInstaller addInInstaller, Uri deploymentManifestUri, AddInInstallationStatus addinSolutionState, String productName, Boolean alreadyInstalled)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
 
 
Followed by:
The customization assembly could not be found or could not be loaded.  You can still save or edit the document.  Contact your administrator or the author of this document for further assistance.
 
I am running Excel 2007 in Windows Vista.  I installed NodeXL with no problems, I did not select custom installation. I have tried uninstalling and reinstalling with no luck and restarting.  Any suggestions?  I also do not have the NodeXL ribbon once I click through the errors either.

#### This work item was migrated from CodePlex
CodePlex work item ID: '14522'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[rmadson@10/26/2009]
Issue solved by viewing past discussions.

**Comment by SMRFoundation** [comment]
[tcap479@10/27/2009]
Are you running Windows Vista on a Mac using either Parallels Desktop or VMware Fusion?

-- Tony

**Comment by SMRFoundation** [comment]
[tcap479@10/27/2009]
Glad to hear it, thanks for letting us know.

-- Tony

**Comment by SMRFoundation** [comment]
[UnknownUser@10/27/2009]

**Comment by SMRFoundation** [comment]
[crisdeluca@5/2/2011]
I was not able to find the solution to this issue in other discussions and am having the same problem. How do I fix this? please asap!!!! THANKS!

**Comment by SMRFoundation** [comment]
[tcap479@5/2/2011]
Please see "How to use NodeXL with Parallels Desktop on a Mac" at http://nodexl.codeplex.com/discussions/253646.

-- Tony

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]

**Comment by SMRFoundation** [comment]
[UnknownUser@5/16/2013]

**Comment by SMRFoundation** [comment]
**Issue closed by _tcap479_ with comment**
Solved by poster.
