### ISSUE TITLE
I am really worried with NodeXl Pro

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#297]
Hello

I am really worried because I can not run NodeXL Pro .

I requested their help in Twitter and through email but have not solved my problem.

I ask you to help me solve this problem

Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Security.SecurityException: The solution cannot be installed because it is signed by a publisher whom you have not yet chosen to trust. If you trust the publisher, add the certificate to the Trusted Publisher list.
   at Microsoft.VisualStudio.Tools.Office.Runtime.OfficeAddInDeploymentManager.VerifyAddInTrust(ClickOnceAddInTrustEvidence evidence)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
The Zone of the assembly that failed was:
MyComputer

#### This work item was migrated from CodePlex
CodePlex work item ID: '64912'
Vote count: '2'

**Comment by SMRFoundation** [comment]
[arber@10/21/2015]
Hello,

 We had a certificate problem some days ago and now it should be fixed. Do you still get this error?

Regards,
Arber

**Comment by SMRFoundation** [comment]
[UnknownUser@5/31/2016]
