### ISSUE TITLE
Can not uninstall basic to upgrade to pro

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#302]
I tried to upgrade to pro and was met with the error message

************** Exception Text **************
System.Deployment.Application.DeploymentException: Unable to install this application because an application with the same identity is already installed. To install this application, either modify the manifest version for this application or uninstall the preexisting application.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

I have tried everything to remove the basic software off the computer, it is worse than a computer virus!
Can you please tell me how I should get this thing off my PC
Thanks

#### This work item was migrated from CodePlex
CodePlex work item ID: '65002'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[MarkJR@11/13/2015]
I get the same error message so I would also appreciate an answer to this problem.

**Comment by SMRFoundation** [comment]
[MarkJR@11/13/2015]
Hi titsalina.

I emailed and got following reply which worked:

_Some users have an issue that blocks install of NodeXL.  This issue can be resolved - please go to the following path before installing NodeXL:

C:\Users\[user_profile]\AppData\Local\Apps\2.0 

You should see two folders: one named Data and another folder with a strange name, that is where the old NodeXL is stored.

Please delete the folder with the strange name and try reinstalling NodeX_L

**Comment by SMRFoundation** [comment]
[titsalina@11/16/2015]
cheers love :)
it worked

**Comment by samuelsaari** [comment]
This does not fix the issue for me. Other suggestions?

**Comment by arber** [comment]
Hello,
May we request that you install Team Viewer 14?

https://www.teamviewer.com/en/download/windows/

This application will allow us to remotely resolve the issue.

When it is installed, please share the "Machine ID#" and Passcode and suggest a time for us to schedule a session with you. Please email info@smrfoundation.org to schedule a time to resolve your issue.

Regards,
Arber
