### ISSUE TITLE
Installation Error (NodeXLBasicExcelTemplate2014Setup)

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#305]
Hi

I'm trying to install NodeXL Basic on a new laptop (no previous NodeXL installations) that's running Excel 2013. Keep getting the error message below. I was testing the installation before registering for the Pro version but now I'm having second thoughts about it... I hope the issue can be resolved quickly. Thanks

Error Message:

Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Deployment.Application.DeploymentDownloadException: Downloading http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Application Files/Smrf.NodeXL.ExcelTemplate_1_0_1_344/SnapGraphMetricCalculatorForCliquesOnly.exe.deploy did not succeed. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

#### This work item was migrated from CodePlex
CodePlex work item ID: '65013'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[arber@1/11/2016]
Hello,

are you still having problems installing NodeXL Basic? Please try downloading the latest version https://nodexl.codeplex.com/releases/view/117659

Regards,
Arber

**Comment by SMRFoundation** [comment]
[christinrj@1/11/2016]
I just tried the link you sent and managed to install it. Thanks!
