### ISSUE TITLE
Issue with installing NodeXL Pro

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#309]
Hello and Merry Christmas.

I am a NodeXL Pro user. Today I tired to open the template, but I did not manage to do so because of the "Update Office Customization" error. I decided to uninstall NodeXL and install the Pro version (downloaded from https://www.nodexlgraphgallery.org/Pages/Registration.aspx) again. I did clean the "C:\Users\User\AppData\Local\Apps\2.0" folder before installing the Pro version again. However, now I cannot install NodeXL Pro because of the "Exception reading manifest from http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto" error. Error details are the following:

Name: 
From: http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: Exception reading manifest from http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto: the manifest may not be valid or the file could not be opened. ---> System.Deployment.Application.InvalidDeploymentException: Manifest XML signature is not valid. ---> System.Security.Cryptography.CryptographicException: SignatureDescription could not be created for the signature algorithm supplied.
   at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
   at System.Deployment.Internal.CodeSigning.SignedCmiManifest.Verify(CmiManifestVerifyFlags verifyFlags)
   at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
   --- End of inner exception stack trace ---
   at System.Deployment.Application.Manifest.AssemblyManifest.ValidateSignature(Stream s)
   at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

Btw, I do not have problems with installing NodeXL Basic.

Could you please help me with resolving this problem. I would be very grateful to you for this.

#### This work item was migrated from CodePlex
CodePlex work item ID: '65038'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[arber@1/11/2016]
Hello,

please install .NET Framework 4.5 https://www.microsoft.com/en-us/download/details.aspx?id=30653

Regards,
Arber
