### ISSUE TITLE
Trouble installing: certificate not trusted

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#314]
Dear Sir/Madam,

When trying to install the earliest version of NodeXL Basic on my machine running Windows 8.1 and Excel 2013 i get the following error. How could I solve this issue?

Sincerely,

Joe Patreas

Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Security.SecurityException: Customized functionality in this application will not work because the certificate used to sign the deployment manifest for NodeXL Excel Template or its location is not trusted. Contact your administrator for further assistance.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
The Zone of the assembly that failed was:
MyComputer

#### This work item was migrated from CodePlex
CodePlex work item ID: '65051'
Vote count: '4'

**Comment by SMRFoundation** [comment]
[arber@1/18/2016]
Hello,

please add http://www.nodexlgraphgallery.org to the "Trusted Sites" in Internet Options.

Regards,
Arber

**Comment by SMRFoundation** [comment]
[Dirty_Joe@1/18/2016]
Great, that worked. Thank you very much!

A hint for anyobody else who tries to do the same thing: Windows is trying to make you type it with the https prefix, hence you have to untick "Require server verification" and type it with just the http prefix as arber previously posted.

Have a nice week,

Joe

**Comment by SMRFoundation** [comment]
[UnknownUser@1/27/2016]

**Comment by SMRFoundation** [comment]
[UnknownUser@5/31/2016]
