### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#316]
I received the following error message when trying to download the software. 

Name: 
From: http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: entryValue
   at Microsoft.VisualStudio.Tools.Applications.Deployment.RegistryStore.Retrieve(String entryName, Object entryValue, CompareDelegate compareMethod)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.MetadataStore.UpdateLastCheckedTime(String subscriptionIDParameter, String subscriptionIDValue, DateTime newLastCheckedTime)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

Before this, I had installed the software but couldn't find it on my desktop to open so I uninstalled and tried to start over.

#### This work item was migrated from CodePlex
CodePlex work item ID: '65059'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[arber@1/25/2016]
Hello,

please try clearing the ClickOnce cache:

1. Open a Command Prompt window as administrator (https://technet.microsoft.com/en-us/library/cc947813%28v=ws.10%29.aspx?f=255&MSPPError=-2147217396)
2. Type this command and hit enter:  rundll32 dfshim CleanOnlineAppCache
 

Regards,
Arber
