### ISSUE TITLE
Object Reference error on startup

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#318]
Hi,

I just installed NodeXL Pro on Windows 10. Yesterday, it was working fine! However today, when I logged back in to check out some of the features, it did not start! I get this error whenever starting up the template:

System.NullReferenceException: Object reference not set to an instance of an object.

And then the NodeXL menu does not show up in the menu bar. Here's the full error text(long) below the post. Please help!

Vlad

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.ThisWorkbook_Startup(Object sender, EventArgs e)
   at Microsoft.Office.Tools.Excel.WorkbookImpl.OnStartup()
   at Microsoft.Office.Tools.Excel.WorkbookImpl.WorkbookExtensionImpl.Microsoft.Office.Tools.EntryPoint.OnStartup()
   at Microsoft.Office.Tools.Excel.WorkbookBase.OnStartup()
   at Smrf.NodeXL.ExcelTemplate.ThisWorkbook.FinishInitialization()
   at Microsoft.Office.Tools.Excel.WorkbookBase.Microsoft.Office.Tools.EntryPoint.FinishInitialization()
   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.ExecuteCustomization.ExecutePhase(ExecutionPhases executionPhases)
   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.ExecuteCustomization.Microsoft.VisualStudio.Tools.Office.Runtime.Interop.IExecuteCustomization2.ExecuteEntryPoints()

************** Loaded Assemblies **************
mscorlib
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE

    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
System
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
Microsoft.VisualStudio.Tools.Office.Runtime
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Runtime/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Runtime.dll
Microsoft.Office.Tools
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Office.Tools/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.dll
Microsoft.VisualStudio.Tools.Applications.Runtime
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Runtime/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Runtime.dll
Microsoft.Office.Tools.Excel.Implementation
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Office.Tools.Excel.Implementation/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.Excel.Implementation.dll
Microsoft.Office.Tools.Common.Implementation
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Office.Tools.Common.Implementation/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.Common.Implementation.dll
Microsoft.Office.Tools.Excel
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Office.Tools.Excel/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.Excel.dll
System.Windows.Forms
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
Microsoft.Office.Tools.Common
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Office.Tools.Common/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.Office.Tools.Common.dll
Microsoft.VisualStudio.Tools.Applications.ServerDocument
Assembly Version: 10.0.0.0
Win32 Version: 10.0.40820.0

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.ServerDocument/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.ServerDocument.dll
System.Drawing
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
Smrf.NodeXL.ExcelTemplate
Assembly Version: 1.0.1.349
Win32 Version: 1.0.1.349

    CodeBase: file:///C:/Users/Vladimir/AppData/Local/Apps/2.0/BQL2ZKLK.N4D/GVTTN275.3PA/smrf..vsto_91729be392989ec5_0001.0000_1a3b2e1819cadc6a/Smrf.NodeXL.ExcelTemplate.DLL
Microsoft.Office.Tools.Excel.v4.0.Utilities
Assembly Version: 10.0.0.0
Win32 Version: 10.0.30319.1

    CodeBase: file:///C:/Users/Vladimir/AppData/Local/Apps/2.0/BQL2ZKLK.N4D/GVTTN275.3PA/smrf..vsto_91729be392989ec5_0001.0000_1a3b2e1819cadc6a/Microsoft.Office.Tools.Excel.v4.0.Utilities.DLL
System.Xml
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
Microsoft.Office.Tools.Common.v4.0.Utilities
Assembly Version: 10.0.0.0
Win32 Version: 10.0.30319.1

    CodeBase: file:///C:/Users/Vladimir/AppData/Local/Apps/2.0/BQL2ZKLK.N4D/GVTTN275.3PA/smrf..vsto_91729be392989ec5_0001.0000_1a3b2e1819cadc6a/Microsoft.Office.Tools.Common.v4.0.Utilities.DLL
Smrf.NodeXL.ApplicationUtil
Assembly Version: 1.0.1.349
Win32 Version: 1.0.1.349

    CodeBase: file:///C:/Users/Vladimir/AppData/Local/Apps/2.0/BQL2ZKLK.N4D/GVTTN275.3PA/smrf..vsto_91729be392989ec5_0001.0000_1a3b2e1819cadc6a/Smrf.NodeXL.ApplicationUtil.DLL
Smrf.NodeXL.Core
Assembly Version: 1.0.1.349
Win32 Version: 1.0.1.349

    CodeBase: file:///C:/Users/Vladimir/AppData/Local/Apps/2.0/BQL2ZKLK.N4D/GVTTN275.3PA/smrf..vsto_91729be392989ec5_0001.0000_1a3b2e1819cadc6a/Smrf.NodeXL.Core.DLL
Smrf.NodeXL.Visualization.Wpf
Assembly Version: 1.0.1.349
Win32 Version: 1.0.1.349

    CodeBase: file:///C:/Users/Vladimir/AppData/Local/Apps/2.0/BQL2ZKLK.N4D/GVTTN275.3PA/smrf..vsto_91729be392989ec5_0001.0000_1a3b2e1819cadc6a/Smrf.NodeXL.Visualization.Wpf.DLL
System.ServiceModel
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
System.Runtime.Serialization
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
SMDiagnostics
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
System.ServiceModel.Internals
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
System.Configuration
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
System.Transactions
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
System.Core
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
System.IdentityModel
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
System.Net.Http
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
System.Security
Assembly Version: 4.0.0.0
Win32 Version: 4.6.1038.0 built by: NETFXREL2

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll

#### This work item was migrated from CodePlex
CodePlex work item ID: '65069'
Vote count: '2'

**Comment by SMRFoundation** [comment]
[arber@1/27/2016]
Hello,

please have a look at this post https://nodexl.codeplex.com/discussions/650548

Regards,
Arber

**Comment by SMRFoundation** [comment]
[UnknownUser@2/11/2016]
