### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#323]
Hi,

I have been trying to install NodeXL and this error proceeds after the download is complete. 

Name: 
From: http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: entryValue
   at Microsoft.VisualStudio.Tools.Applications.Deployment.RegistryStore.Retrieve(String entryName, Object entryValue, CompareDelegate compareMethod)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.MetadataStore.UpdateLastCheckedTime(String subscriptionIDParameter, String subscriptionIDValue, DateTime newLastCheckedTime)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

Could you please let me know if there is a way to fix this issue?

Thanks,
Kywildcatsfan11

#### This work item was migrated from CodePlex
CodePlex work item ID: '65083'
Vote count: '4'

**Comment by SMRFoundation** [comment]
[arber@2/15/2016]
Hello,

please try the following:

1. Open a "Command Prompt" window as Administrator
2. Run this command:  rundll32 dfshim CleanOnlineAppCache
3. Try installing again

If the above method fails:

1. Open  "File Explorer"
2. Paste this in the address bar: %USERPROFILE%\AppData\Local\Apps\2.0 
3. There should be 2 folders: Data and another one with a strange name
4. Delete the folder with the strange name.
5. Try installing again

Regards,
Arber

**Comment by SMRFoundation** [comment]
[UnknownUser@2/24/2016]
