### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#328]
I'm getting the following error when I trying to install NodeXL. Do you know a solution to this? I was hoping to demonstrate the program for a class lecture.

Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Security.SecurityException: Customized functionality in this application will not work because the certificate used to sign the deployment manifest for NodeXL Excel Template or its location is not trusted. Contact your administrator for further assistance.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
The Zone of the assembly that failed was:
MyComputer

#### Attachments
[Screen Shot 2016-02-24 at 11.41.58.png](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=NodeXL&WorkItemId=65097&FileAttachmentId=8737)

#### This work item was migrated from CodePlex
CodePlex work item ID: '65097'
Vote count: '3'

**Comment by SMRFoundation** [comment]
[JamesHKC@2/24/2016]
I'm having the same problem. I've tried running as the admin and no luck. Has anyone found a solution to this one?

**Comment by SMRFoundation** [comment]
[arber@2/27/2016]
Hello,

please have a look at this post https://nodexl.codeplex.com/discussions/650324

Regards,
Arber

**Comment by SMRFoundation** [comment]
[UnknownUser@5/31/2016]
