### ISSUE TITLE
Error Message - SOS please!

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#351]
I couldn't even run the app. Please help me.

An error occurred trying to download 'http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Smrf.NodeXL.ExcelTemplate.vsto'.

See the setup log file located at 'C:\Users\JEROME~1\AppData\Local\Temp\VSDC216.tmp\install.log' for more information.

#### This work item was migrated from CodePlex
CodePlex work item ID: '65165'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[Profdavis@6/1/2016]
Yes, I am receiving the exact same error.  Does anyone have a solution for this?\

Thanks!

Here are the details in the error message . . .

Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Security.SecurityException: Customized functionality in this application will not work because the certificate used to sign the deployment manifest for NodeXL Excel Template or its location is not trusted. Contact your administrator for further assistance.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
The Zone of the assembly that failed was:
MyComputer
