### ISSUE TITLE
Can't install NodeXL Pro

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#361]
Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: File, Twitter.jpg, has a different computed hash than specified in manifest.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

#### This work item was migrated from CodePlex
CodePlex work item ID: '65192'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[l33t8l@8/26/2016]
I installed Visual Studio 2010 Tools for Office Runtime to get past this issue.  Now the problem is using Excel 2016.
