### ISSUE TITLE
NodeXL Basic Excel Template error

### ISSUE THREAD

**Issue by GavinRayner** [SMRFoundation/NodeXLBasic#393]
I'm trying to install NodeXL Basic Template on a Windows 10 Enterprise laptop (Version 1803, OS build 17134.345) with MS Excel 2016 (16.0.4738.1000) 64-bit.
There are no errors when I run NodeXLBasicExcelTemplate2018Setup.exe
Then when I try to open the NodeXL template I get:
"Microsoft Office Customization Installer
Updating Office customization
There was an error during installation.
Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLBasicSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Security.Cryptography.CryptographicException: SignatureDescription could not be created for the signature algorithm supplied.
   at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
   at System.Security.Cryptography.Xml.ManifestSignedXml.VerifyStrongNameSignature(XmlElement signatureNode)
   at System.Security.Cryptography.Xml.ManifestSignedXml.VerifySignature(X509RevocationFlag revocationFlag, X509RevocationMode revocationMode)
   at System.Security.Cryptography.ManifestSignatureInformation.VerifySignature(ActivationContext application, ManifestKinds manifests, X509RevocationFlag revocationFlag, X509RevocationMode revocationMode)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyCertificateSignature(ActivationContext context, OnlineOfflineState offlineState, String productName, DeploymentSignatureInformation& signatureInformation)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()"
   
I suspect it's something to do with .NET versions? Here's what I have installed:
C:\MyDocs>NET_Detector_cli.exe

Raymondcc .NET Detector CLI

Installed:
.NET Framework 2.0 Service Pack 2
.NET Framework 3.0 Service Pack 2
.NET Framework 3.5 Service Pack 1
.NET Framework 4.7.2

Any suggestion greatly appreciated.

Regards,

Gavin

**Comment by arber** [comment]
Hello,

Try installing VSTO 2010 https://www.microsoft.com/en-us/download/details.aspx?id=48217

Regards,
Arber

**Comment by GavinRayner** [comment]
> 
> 
> Hello,
> 
> Try installing VSTO 2010 https://www.microsoft.com/en-us/download/details.aspx?id=48217
> 
> Regards,
> Arber

Thanks for the suggestion Arber, I tried that but I'm still getting the same error.

Regards, Gavin

**Comment by arber** [comment]
Hello Gavin,

On some systems (often in large corporations or universities) access to websites needed by NodeXL are blocked.  To resolve this issue, these web site addresses can be added to a list of trusted sites.

NodeXL needs access to the NodeXLGraphGallery.org web site.

To enable access to this web site, from the Windows Start menu, search for "Internet Options" and then select "Security" and "Trusted Sites".

There is a button below the Trusted Sites menu: "Sites" - select this to add the NodeXLGraphGallery.org web site to the exception list:


The Trusted Sites dialog will allow you to enter the following web addresses:
http://www.nodexlgraphgallery.org
https://www.nodexlgraphgallery.org

NOTE: It is necessary to UNCHECK "Require server verification (https:) for all sites in this zone.

Regards,
Arber

**Comment by GavinRayner** [comment]
Thanks for the suggestion Arber. I've tried that but it's still not working.

Regards,
Gavin

**Comment by arber** [comment]
Hello Gavin,

I may have to take a look myself. Please send an e-mail at info@smrfoundation.org and I will send you the steps we can try next.

Regards,
Arber
