### ISSUE TITLE
Cannot install NodeXL Pro: File, Update.jpg, has a different computed hash than specified in manifest.

### ISSUE THREAD

**Issue by karlomarco** [SMRFoundation/NodeXLBasic#394]
Hello there,

I have not been able to install NodeXL Pro as I keep getting the following error after the installer downloads the 8MB file:

Name: NodeXL Excel Template
From: http://www.nodexlgraphgallery.org/NodeXLSetup/Smrf.NodeXL.ExcelTemplate.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: File, Update.jpg, has a different computed hash than specified in manifest.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

Please help!

Regards,
Karlo

**Comment by arber** [comment]
Hello,

This usually happens for 2 reasons:

1. An antivirus/firewall is blocking the setup from downloading the appropriate files. Please try disabling your antivirus/firewall and try installing NodeXL

2. The ClickOnce cache got corrupted. To reset it please follow these steps:
   a. Go to the following path: C:\Users\[user_profile]\AppData\Local\Apps
   b. Delete the folder named "2.0"
   c. Try installing NodeXL

If you feel uncomfortable trying the above steps, we can try a remote support session. Please send an e-mail at info@smrfoundation.org requesting a remote support session.

Regards,
Arber
