### ISSUE TITLE
NodeXL can't open the Kite Network Example

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#42]
Hi, 
everytime I try to open the Kite Network Example, I get the error message as displayed below... Could it be that something went wrong with the installation of NodeXL? It happens regularly that the NodeXL ribbon doesn't appear when opening the programme...
 
Many thanks!
 
Dorien
 
Customization does not have the permissions required to create an application domain.
 
 
************** Exception Text **************
Microsoft.VisualStudio.Tools.Applications.Runtime.CannotCreateCustomizationDomainException: Customization does not have the permissions required to create an application domain. ---> System.Security.SecurityException: Customized functionality in this program will not work because the location of Kite_Example[1].xlsx is not in the Office Trusted Locations list, or all trusted locations are disabled. Contact your administrator for further assistance.
   at Microsoft.VisualStudio.Tools.Office.Runtime.RuntimeUtilities.VerifyDocumentIsTrusted(String documentFullLocation, String documentName)
   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.CreateCustomizationDomainInternal(String documentFullLocation, String documentName, String assemblyLocation, Boolean showUIDuringDeployment, IntPtr hostServiceProvider, IntPtr& executor)
The Zone of the assembly that failed was:
MyComputer
   --- End of inner exception stack trace ---
 
 
************** Loaded Assemblies **************
mscorlib
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)

    CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
Microsoft.VisualStudio.Tools.Office.Runtime.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.1

    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Office.Runtime.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Office.Runtime.v9.0.dll
System
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)

    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
System.Core
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.1 built by: SP

    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
System.AddIn
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.1 built by: SP

    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.AddIn/3.5.0.0__b77a5c561934e089/System.AddIn.dll
Microsoft.VisualStudio.Tools.Applications.Hosting.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.1

    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Hosting.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Hosting.v9.0.dll
Microsoft.VisualStudio.Tools.Applications.ServerDocument.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.1

    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.ServerDocument.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.ServerDocument.v9.0.dll
Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0
Assembly Version: 9.0.0.0
Win32 Version: 9.0.30729.1

    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0/9.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Tools.Applications.Runtime.v9.0.dll

#### This work item was migrated from CodePlex
CodePlex work item ID: '19828'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@1/27/2011]
On the Kite Network Example problem, please see "About Excel's Trusted Locations" at http://nodexl.codeplex.com/Thread/View.aspx?ThreadId=72820.

On the missing NodeXL tab problem, you have to start NodeXL from the Windows Start menu.  In Windows 7, click Start menu, then "All Programs", then "Microsoft NodeXL,” then "NodeXL Excel Template."

-- Tony

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]
