### ISSUE TITLE
Customization Problem Opening Files in Parallels

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#48]
I am using nodexl in parallels, and I am having trouble opening existing files.  I am trying to open an example from one of my books (SeriousEats_example.xlsx) but I am getting a customization error. I have tried the trust location and unsharing everything between mac-windows.. Below is the error details that come up while trying to open the file.  thanks to anyone that can help.
 
 
 
Name: 
From: file:///C:/Documents and Settings/Owner/My Documents/Microsoft.NodeXL.ExcelTemplate.vsto
 
Downloading file:///C:/Documents and Settings/Owner/My Documents/Microsoft.NodeXL.ExcelTemplate.vsto did not succeed.
 
************** Exception Text **************
System.Deployment.Application.DeploymentDownloadException: Downloading file:///C:/Documents and Settings/Owner/My Documents/Microsoft.NodeXL.ExcelTemplate.vsto did not succeed. ---> System.Net.WebException: Could not find file 'C:\Documents and Settings\Owner\My Documents\Microsoft.NodeXL.ExcelTemplate.vsto'. ---> System.Net.WebException: Could not find file 'C:\Documents and Settings\Owner\My Documents\Microsoft.NodeXL.ExcelTemplate.vsto'. ---> System.IO.FileNotFoundException: Could not find file 'C:\Documents and Settings\Owner\My Documents\Microsoft.NodeXL.ExcelTemplate.vsto'.
File name: 'C:\Documents and Settings\Owner\My Documents\Microsoft.NodeXL.ExcelTemplate.vsto'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.FileWebRequest.GetResponse()
   at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

#### This work item was migrated from CodePlex
CodePlex work item ID: '20353'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@3/29/2011]
Are you able to create a new NodeXL workbook, as opposed to opening an existing one?  (In the Windows Start menu, click "All Programs" (Windows 7 or Vista) or "Programs" (XP), then "Microsoft NodeXL," then "Excel Template.")

 -- Tony

**Comment by SMRFoundation** [comment]
[claff319@3/29/2011]
thanks for a quick response.  Yes i am able to open up the Excel Template, and everything works excellent.  I am able to use everything in the nodexl tab as well as the design tab.  The graph and everything works fine in my own workbook,  the problem occurs when trying to open an existing .xlsx file (kite example, Serious Eats example).  The file opens up, starts to load, then i get hit with the customization error along with the details shown above.  After closing this error window, the file loads in a regular excel workbook without the nodexl and design capability tabs.  If you have any ideas on troubleshooting this problem i would greatly appreciate it.  And once again, thanks for the help and quick reply.

**Comment by SMRFoundation** [comment]
[tcap479@3/29/2011]
I think you are using an old version of that file that was meant for a much earlier version of NodeXL.  Can you point me to the place where you obtained the file?  I'll check it out.

(I assume that you are using a recent version of NodeXL.  The current version is 1.0.1.164.  You can tell what version you have by going to NodeXL, Help, About Microsoft NodeXL in the Excel Ribbon.)

-- Tony

-- Tony

**Comment by SMRFoundation** [comment]
[claff319@3/30/2011]
The file I'm referring to can be found at:   http://casci.umd.edu/NodeXL_Teaching   -- It is located on the middle of the page under  "NodeXL Sample Files (version 1.0.1.117 or later, for 32-bit or 64-bit machines)"

The current version of NODEXL i am using is v. 1.0.1.113  - I downloaded the older version because the book we follow uses this version and i didn't want to run into any problem (ironically lol).  Is it possible that i need to download a newer version of NODEXL in order to open these files?  Thanks again!

**Comment by SMRFoundation** [comment]
[tcap479@3/30/2011]
There was a major change in NodeXL after version 1.0.1.113.  I won't bore you with the details, but it means that the files on the Web site you pointed me to won't work with version 1.0.1.113.

But that's okay, you can work around it without having to install the latest version of NodeXL.  Do the following:

1. Open Serious_Eats.xlsx.

2. Close the error messages that appear.

3. Create a new NodeXL workbook using the Windows Start menu.

4. Copy columns A and B from the Serious_Eats.xlsx workbook to your new NodeXL workbook.

5. Use your new NodeXL workbook, which is now a copy of Serious_Eats.xlsx.

-- Tony

**Comment by SMRFoundation** [comment]
[claff319@4/5/2011]
Thanks for all the help Tony, I ended up downloading the latest release of NodeXL and it worked after that.  I guess my initial thought of downloading the version my book used (old version) was actually the problem.  Thanks for all the help, I appreciate it.

**Comment by SMRFoundation** [comment]
[tcap479@4/5/2011]
Thanks for letting me know.

For others reading this: This was not a problem involving Parallels after all.  It was just an issue with using a newer NodeXL workbook with an old version of the program.

-- Tony

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]
