### ISSUE TITLE
Grouph Metrics

### ISSUE THREAD

**Issue by SMRFoundation** [SMRFoundation/NodeXLBasic#90]
NodeXL
An unexpected problem occurred.  If it occurs again, please copy the details to the clipboard by typing Ctrl-C, then post the details to http://www.codeplex.com/NodeXL/Thread/List.aspx.
 
 
 
Details:
 
 
 
[KeyNotFoundException]: The given key was not present in the dictionary.
 
 
 
   at System.ThrowHelper.ThrowKeyNotFoundException()
 
   at System.Collections.Generic.Dictionary2.get_Item(TKey key)    at Smrf.NodeXL.Algorithms.IntergroupEdgeCalculator.IncidentEdgeShouldBeCounted(IEdge oIncidentEdge, IVertex oVertexInGroup1, Int32 iGroup1Index, Dictionary2 oGroupIndexDictionary, Boolean bUseDirectedness, Boolean bGraphIsDirected, Int32& iGroup2Index)
 
   at Smrf.NodeXL.Algorithms.IntergroupEdgeCalculator.TryCalculateGraphMetrics(IGraph graph, BackgroundWorker backgroundWorker, IList1 groups, Boolean useDirectedness, IList1& graphMetrics)
 
   at Smrf.NodeXL.ExcelTemplate.IntergroupEdgeCalculator2.TryCalculateGraphMetrics(IGraph graph, CalculateGraphMetricsContext calculateGraphMetricsContext, GraphMetricColumn[]& graphMetricColumns)
 
   at Smrf.NodeXL.ExcelTemplate.GraphMetricCalculationManager.CalculateGraphMetricsAsyncInternal(CalculateGraphMetricsAsyncArgs oCalculateGraphMetricsAsyncArgs, BackgroundWorker oBackgroundWorker, DoWorkEventArgs oDoWorkEventArgs)
 
   at Smrf.NodeXL.ExcelTemplate.GraphMetricCalculationManager.BackgroundWorker_DoWork(Object sender, DoWorkEventArgs e)
 
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
 
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
OK   

 
Can anyone translate? Anyway to get around this error?

#### This work item was migrated from CodePlex
CodePlex work item ID: '22166'
Vote count: '1'

**Comment by SMRFoundation** [comment]
[tcap479@2/6/2012]
The "KeyNotFoundException" problem is a known bug that has been fixed in the latest release of NodeXL, which you can download from http://nodexl.codeplex.com/releases.

You do not need to uninstall your current version of NodeXL before installing the latest version.  Just run Setup.exe in the latest release.

-- Tony

**Comment by SMRFoundation** [comment]
[UnknownUser@2/21/2013]
